version: "3.5"
services:
  vits:
#    build: .
    image: cuda:11.8.0-devel-ubuntu20.04-py311
    shm_size: '2G'
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8888
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
